version: "3.8"

services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      - PYTHONPATH=/rpa
      - MONGO_URI=mongodb://mongo:27017/
    volumes:
      - .:/rpa
    command: python -m rpa.app.main

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
